#!/usr/bin/env python3
"""
Plot HRRR ESMF vs sflux Comparison

This script compares wind speed from HRRR data processed through the ESMF mesh
workflow with sflux HRRR data generated by nosofs.

Prerequisites:
--------------
1. Conda environment with required packages:
   conda activate ncl_env

   Required packages: numpy, matplotlib, netCDF4, scipy

   To create the environment:
   conda create -n ncl_env python=3.11 numpy matplotlib netCDF4 scipy -c conda-forge
   conda activate ncl_env

2. Input files:
   - HRRR ESMF file: hrrr_t05z_f01.nc (from ESMF mesh workflow)
     NOTE: Use t05z.f01 (not t06z.f00) due to HRRR production latency (~45 min)
   - sflux HRRR file: sflux_air_2.1.nc (from nosofs run)

Usage:
------
   conda activate ncl_env
   python plot_hrrr_sflux_comparison.py

   Or with custom paths:
   python plot_hrrr_sflux_comparison.py --hrrr /path/to/hrrr.nc --sflux /path/to/sflux_air_2.nc

Output:
-------
   hrrr_sflux_comparison_jet.png

IMPORTANT - HRRR Temporal Data Issue:
-------------------------------------
HRRR has ~45 minute production latency. For 06Z valid time:
- hrrr.t06z.wrfsfcf00.grib2 (analysis) is NOT available until ~06:45Z
- nosofs uses hrrr.t05z.wrfsfcf01.grib2 (05Z + 1hr forecast = valid 06Z)

Always use the forecast file from the previous cycle for real-time operations.

Author: Adapted for SECOFS UFS-Coastal transition
Date: January 2026
"""

import argparse
import matplotlib
matplotlib.use('Agg')
import numpy as np
import matplotlib.pyplot as plt
from netCDF4 import Dataset
from scipy.interpolate import griddata
import os


def plot_hrrr_sflux_comparison(hrrr_file, sflux_file, output_file, timestep=3):
    """
    Create 3-panel comparison plot: HRRR ESMF, sflux HRRR, and difference.

    Parameters
    ----------
    hrrr_file : str
        Path to HRRR NetCDF file from ESMF workflow
    sflux_file : str
        Path to sflux_air_2.*.nc file from nosofs
    output_file : str
        Path for output PNG file
    timestep : int
        sflux timestep index (default 3 for 06Z when HRRR starts at 03Z hourly)
    """

    print(f"Loading HRRR ESMF data: {hrrr_file}")
    ds_hrrr = Dataset(hrrr_file, 'r')

    hrrr_lat = ds_hrrr.variables['latitude'][:]
    hrrr_lon = ds_hrrr.variables['longitude'][:]
    hrrr_u = ds_hrrr.variables['UGRD_10maboveground'][0, :, :]
    hrrr_v = ds_hrrr.variables['VGRD_10maboveground'][0, :, :]
    hrrr_wspd = np.sqrt(hrrr_u**2 + hrrr_v**2)

    # Convert longitude to -180 to 180 if needed
    hrrr_lon = np.where(hrrr_lon > 180, hrrr_lon - 360, hrrr_lon)
    ds_hrrr.close()

    print(f"Loading sflux HRRR data: {sflux_file}")
    ds_sflux = Dataset(sflux_file, 'r')

    # Print time info
    time_vals = ds_sflux.variables['time'][:]
    time_units = ds_sflux.variables['time'].units
    print(f"  Time units: {time_units}")
    print(f"  Using timestep {timestep}: {time_vals[timestep]:.4f} days = {time_vals[timestep]*24:.1f} hours")

    sflux_lat = ds_sflux.variables['lat'][:]
    sflux_lon = ds_sflux.variables['lon'][:]
    sflux_u = ds_sflux.variables['uwind'][timestep, :, :]
    sflux_v = ds_sflux.variables['vwind'][timestep, :, :]
    sflux_wspd = np.sqrt(sflux_u**2 + sflux_v**2)

    sflux_lon = np.where(sflux_lon > 180, sflux_lon - 360, sflux_lon)
    ds_sflux.close()

    print(f"HRRR ESMF grid: {hrrr_wspd.shape}")
    print(f"sflux HRRR grid: {sflux_wspd.shape}")

    # Domain bounds (SECOFS region)
    lon_min, lon_max = -85, -65
    lat_min, lat_max = 18, 40

    # Check if grids are the same size
    same_grid = (hrrr_wspd.shape == sflux_wspd.shape)

    if same_grid:
        print("Grids are identical - no interpolation needed")
        hrrr_on_sflux = hrrr_wspd
    else:
        print("Interpolating HRRR to sflux grid...")
        # HRRR has 2D lat/lon (curvilinear grid)
        hrrr_points = np.column_stack((hrrr_lon.flatten(), hrrr_lat.flatten()))
        hrrr_values = hrrr_wspd.flatten()
        sflux_points = np.column_stack((sflux_lon.flatten(), sflux_lat.flatten()))

        hrrr_on_sflux = griddata(hrrr_points, hrrr_values, sflux_points, method='linear')
        hrrr_on_sflux = hrrr_on_sflux.reshape(sflux_wspd.shape)

    # Calculate difference
    diff = hrrr_on_sflux - sflux_wspd

    # Statistics
    valid_mask = ~np.isnan(diff)
    corr = np.corrcoef(hrrr_on_sflux[valid_mask].flatten(),
                       sflux_wspd[valid_mask].flatten())[0, 1]
    rmse = np.sqrt(np.nanmean(diff**2))

    print(f"\nStatistics:")
    print(f"  Correlation: {corr:.6f}")
    print(f"  RMSE: {rmse:.6f} m/s")

    # Create figure with 3 columns
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))

    vmin, vmax = 0, 14

    # Plot 1: HRRR (ESMF workflow)
    ax1 = axes[0]
    c1 = ax1.pcolormesh(hrrr_lon, hrrr_lat, hrrr_wspd, cmap='jet',
                        vmin=vmin, vmax=vmax, shading='auto')
    ax1.set_xlim(lon_min, lon_max)
    ax1.set_ylim(lat_min, lat_max)
    ax1.set_xlabel('Longitude')
    ax1.set_ylabel('Latitude')
    ax1.set_title('HRRR (ESMF Workflow)\n3km grid',
                  fontsize=11, fontweight='bold')
    plt.colorbar(c1, ax=ax1, shrink=0.8, label='m/s')

    # Plot 2: sflux HRRR
    ax2 = axes[1]
    c2 = ax2.pcolormesh(sflux_lon, sflux_lat, sflux_wspd, cmap='jet',
                        vmin=vmin, vmax=vmax, shading='auto')
    ax2.set_xlim(lon_min, lon_max)
    ax2.set_ylim(lat_min, lat_max)
    ax2.set_xlabel('Longitude')
    ax2.set_ylabel('Latitude')
    ax2.set_title('sflux HRRR (nosofs)\ninterpolated grid',
                  fontsize=11, fontweight='bold')
    plt.colorbar(c2, ax=ax2, shrink=0.8, label='m/s')

    # Plot 3: Difference
    ax3 = axes[2]
    diff_max = max(0.05, np.nanmax(np.abs(diff)))
    c3 = ax3.pcolormesh(sflux_lon, sflux_lat, diff, cmap='jet',
                        vmin=-diff_max, vmax=diff_max, shading='auto')
    ax3.set_xlim(lon_min, lon_max)
    ax3.set_ylim(lat_min, lat_max)
    ax3.set_xlabel('Longitude')
    ax3.set_ylabel('Latitude')
    ax3.set_title(f'Difference (ESMF - sflux)\nCorr: {corr:.4f} | RMSE: {rmse:.3f} m/s',
                  fontsize=11, fontweight='bold')
    plt.colorbar(c3, ax=ax3, shrink=0.8, label='m/s')

    plt.suptitle('10m Wind Speed: HRRR ESMF vs sflux Comparison',
                 fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()

    plt.savefig(output_file, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"\nSaved: {output_file}")

    return corr, rmse


def main():
    parser = argparse.ArgumentParser(
        description='Plot HRRR ESMF vs sflux comparison',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)

    parser.add_argument('--hrrr', type=str,
                        default='hrrr_t05z_f01.nc',
                        help='Path to HRRR NetCDF from ESMF workflow')
    parser.add_argument('--sflux', type=str,
                        default='../../../../sflux/sflux_air_2.1.nc',
                        help='Path to sflux_air_2.*.nc from nosofs')
    parser.add_argument('--output', type=str,
                        default='hrrr_sflux_comparison_jet.png',
                        help='Output PNG filename')
    parser.add_argument('--timestep', type=int, default=3,
                        help='sflux timestep index (default: 3 for 06Z with hourly HRRR)')

    args = parser.parse_args()

    # Verify input files exist
    if not os.path.exists(args.hrrr):
        print(f"Error: HRRR file not found: {args.hrrr}")
        return 1
    if not os.path.exists(args.sflux):
        print(f"Error: sflux file not found: {args.sflux}")
        return 1

    plot_hrrr_sflux_comparison(args.hrrr, args.sflux, args.output, args.timestep)
    return 0


if __name__ == '__main__':
    exit(main())
