#!/usr/bin/env python3
"""
Plot GFS ESMF vs sflux Comparison

This script compares wind speed from GFS data processed through the ESMF mesh
workflow with sflux GFS data generated by nosofs.

Prerequisites:
--------------
1. Conda environment with required packages:
   conda activate ncl_env

   Required packages: numpy, matplotlib, netCDF4, scipy

   To create the environment:
   conda create -n ncl_env python=3.11 numpy matplotlib netCDF4 scipy -c conda-forge
   conda activate ncl_env

2. Input files:
   - GFS ESMF file: gfs_20251231_06z.nc (from ESMF mesh workflow)
   - sflux GFS file: sflux_air_1.1.nc (from nosofs run)

Usage:
------
   conda activate ncl_env
   python plot_gfs_sflux_comparison.py

   Or with custom paths:
   python plot_gfs_sflux_comparison.py --gfs /path/to/gfs.nc --sflux /path/to/sflux_air_1.nc

Output:
-------
   gfs_sflux_comparison_jet.png

Author: Adapted for SECOFS UFS-Coastal transition
Date: January 2026
"""

import argparse
import matplotlib
matplotlib.use('Agg')
import numpy as np
import matplotlib.pyplot as plt
from netCDF4 import Dataset
from scipy.interpolate import griddata
import os


def plot_gfs_sflux_comparison(gfs_file, sflux_file, output_file, timestep=1):
    """
    Create 3-panel comparison plot: GFS ESMF, sflux GFS, and difference.

    Parameters
    ----------
    gfs_file : str
        Path to GFS NetCDF file from ESMF workflow
    sflux_file : str
        Path to sflux_air_1.*.nc file from nosofs
    output_file : str
        Path for output PNG file
    timestep : int
        sflux timestep index (default 1 for 06Z when time starts at 03Z)
    """

    print(f"Loading GFS ESMF data: {gfs_file}")
    ds_gfs = Dataset(gfs_file, 'r')

    gfs_lat = ds_gfs.variables['latitude'][:]
    gfs_lon = ds_gfs.variables['longitude'][:]
    gfs_u = ds_gfs.variables['UGRD_10maboveground'][0, :, :]
    gfs_v = ds_gfs.variables['VGRD_10maboveground'][0, :, :]
    gfs_wspd = np.sqrt(gfs_u**2 + gfs_v**2)

    # Convert longitude to -180 to 180 if needed
    gfs_lon = np.where(gfs_lon > 180, gfs_lon - 360, gfs_lon)
    ds_gfs.close()

    print(f"Loading sflux GFS data: {sflux_file}")
    ds_sflux = Dataset(sflux_file, 'r')

    # Print time info
    time_vals = ds_sflux.variables['time'][:]
    time_units = ds_sflux.variables['time'].units
    print(f"  Time units: {time_units}")
    print(f"  Using timestep {timestep}: {time_vals[timestep]} days")

    sflux_lat = ds_sflux.variables['lat'][:]
    sflux_lon = ds_sflux.variables['lon'][:]
    sflux_u = ds_sflux.variables['uwind'][timestep, :, :]
    sflux_v = ds_sflux.variables['vwind'][timestep, :, :]
    sflux_wspd = np.sqrt(sflux_u**2 + sflux_v**2)

    sflux_lon = np.where(sflux_lon > 180, sflux_lon - 360, sflux_lon)
    ds_sflux.close()

    print(f"GFS grid: {gfs_wspd.shape[1]}x{gfs_wspd.shape[0]}")
    print(f"sflux grid: {sflux_wspd.shape[1]}x{sflux_wspd.shape[0]}")

    # Domain bounds (SECOFS region)
    lon_min, lon_max = -85, -65
    lat_min, lat_max = 18, 40

    # Create GFS meshgrid and interpolate to sflux grid
    gfs_lon2d, gfs_lat2d = np.meshgrid(gfs_lon, gfs_lat)
    gfs_points = np.column_stack((gfs_lon2d.flatten(), gfs_lat2d.flatten()))
    gfs_values = gfs_wspd.flatten()
    sflux_points = np.column_stack((sflux_lon.flatten(), sflux_lat.flatten()))

    print("Interpolating GFS to sflux grid...")
    gfs_on_sflux = griddata(gfs_points, gfs_values, sflux_points, method='linear')
    gfs_on_sflux = gfs_on_sflux.reshape(sflux_wspd.shape)

    # Calculate difference
    diff = gfs_on_sflux - sflux_wspd

    # Statistics
    valid_mask = ~np.isnan(diff)
    corr = np.corrcoef(gfs_on_sflux[valid_mask].flatten(),
                       sflux_wspd[valid_mask].flatten())[0, 1]
    rmse = np.sqrt(np.nanmean(diff**2))

    print(f"\nStatistics:")
    print(f"  Correlation: {corr:.6f}")
    print(f"  RMSE: {rmse:.6f} m/s")

    # Create figure with 3 columns
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))

    vmin, vmax = 0, 14

    # Plot 1: GFS (ESMF workflow)
    ax1 = axes[0]
    c1 = ax1.pcolormesh(gfs_lon, gfs_lat, gfs_wspd, cmap='jet',
                        vmin=vmin, vmax=vmax, shading='auto')
    ax1.set_xlim(lon_min, lon_max)
    ax1.set_ylim(lat_min, lat_max)
    ax1.set_xlabel('Longitude')
    ax1.set_ylabel('Latitude')
    ax1.set_title(f'GFS (ESMF Workflow)\n{gfs_wspd.shape[1]}x{gfs_wspd.shape[0]} grid',
                  fontsize=11, fontweight='bold')
    plt.colorbar(c1, ax=ax1, shrink=0.8, label='m/s')

    # Plot 2: sflux GFS
    ax2 = axes[1]
    c2 = ax2.pcolormesh(sflux_lon, sflux_lat, sflux_wspd, cmap='jet',
                        vmin=vmin, vmax=vmax, shading='auto')
    ax2.set_xlim(lon_min, lon_max)
    ax2.set_ylim(lat_min, lat_max)
    ax2.set_xlabel('Longitude')
    ax2.set_ylabel('Latitude')
    ax2.set_title(f'sflux GFS (nosofs)\n{sflux_wspd.shape[1]}x{sflux_wspd.shape[0]} grid',
                  fontsize=11, fontweight='bold')
    plt.colorbar(c2, ax=ax2, shrink=0.8, label='m/s')

    # Plot 3: Difference
    ax3 = axes[2]
    diff_max = max(0.05, np.nanmax(np.abs(diff)))
    c3 = ax3.pcolormesh(sflux_lon, sflux_lat, diff, cmap='jet',
                        vmin=-diff_max, vmax=diff_max, shading='auto')
    ax3.set_xlim(lon_min, lon_max)
    ax3.set_ylim(lat_min, lat_max)
    ax3.set_xlabel('Longitude')
    ax3.set_ylabel('Latitude')
    ax3.set_title(f'Difference (ESMF - sflux)\nCorr: {corr:.4f} | RMSE: {rmse:.3f} m/s',
                  fontsize=11, fontweight='bold')
    plt.colorbar(c3, ax=ax3, shrink=0.8, label='m/s')

    plt.suptitle('10m Wind Speed: GFS ESMF vs sflux Comparison',
                 fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()

    plt.savefig(output_file, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"\nSaved: {output_file}")

    return corr, rmse


def main():
    parser = argparse.ArgumentParser(
        description='Plot GFS ESMF vs sflux comparison',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)

    parser.add_argument('--gfs', type=str,
                        default='gfs_20251231_06z.nc',
                        help='Path to GFS NetCDF from ESMF workflow')
    parser.add_argument('--sflux', type=str,
                        default='../../../../sflux/sflux_air_1.1.nc',
                        help='Path to sflux_air_1.*.nc from nosofs')
    parser.add_argument('--output', type=str,
                        default='gfs_sflux_comparison_jet.png',
                        help='Output PNG filename')
    parser.add_argument('--timestep', type=int, default=1,
                        help='sflux timestep index (default: 1 for 06Z)')

    args = parser.parse_args()

    # Verify input files exist
    if not os.path.exists(args.gfs):
        print(f"Error: GFS file not found: {args.gfs}")
        return 1
    if not os.path.exists(args.sflux):
        print(f"Error: sflux file not found: {args.sflux}")
        return 1

    plot_gfs_sflux_comparison(args.gfs, args.sflux, args.output, args.timestep)
    return 0


if __name__ == '__main__':
    exit(main())
